package com.think.boot.domain;

import java.io.Serializable;

/**
 * Model class of class.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Class implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Long id;

	/** classid. */
	private Integer classid;

	/**
	 * Constructor.
	 */
	public Class() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Long getId() {
		return this.id;
	}

	/**
	 * Set the classid.
	 * 
	 * @param classid
	 *            classid
	 */
	public void setClassid(Integer classid) {
		this.classid = classid;
	}

	/**
	 * Get the classid.
	 * 
	 * @return classid
	 */
	public Integer getClassid() {
		return this.classid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Class other = (Class) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
